services:
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./database/pqdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
